# bert_finetune.yaml file

train_data_file: 'aug_dataset.txt'
val_data_file: 'val_aug_dataset.txt'
model_name: 'bert-large-uncased'
save_model_directory: 'BERT_aug'
num_train_epochs: 10
batch_size: 16
eval_steps: 30000
save_steps: 30000
logging_steps: 2000
mlm_probability: 0.15