# bert_finetune.yaml file

train_data_file: '../../../data/non-specificity/aug/shuffled_aug_dataset_lower_case.txt'
val_data_file: '../../../data/non-specificity/aug/val_aug_dataset_lower_case.txt'
model_name: 'bert-large-uncased'
save_model_directory: 'BERT_aug'
num_train_epochs: 7
batch_size: 4
eval_steps: 30000
save_steps: 30000
logging_steps: 2000
mlm_probability: 0.15