main: &main
    name: concat
    data_dir: ./data/train/
    truncate_length:  512
    preprocessor:
        name: answerbertPreprocessor
        tokenizer:
            name: AutoTokenizer
            init_params:
                pretrained_model_name_or_path: albert-base-v1
train:
    <<: *main
    file_path: ./data/train/Task_1_train.jsonl
    split: train
val:
    <<: *main
    file_path: ./data/train/Task_1_dev.jsonl
    split: val