trainer_name: gabert
version: 1.0
main_config: &main
    seed: !!int 42
    metrics:

      - type: sklearn_f1
        params:
          average: macro

      - type: sklearn_p
        params:
          average: macro

      - type: sklearn_r
        params:
          average: macro

      - type: sklearn_acc
        params:
            normalize: True

    device:
        name: 'cpu'

train: &train
    # Change to different value if not using max_steps
    <<: *main
    # Can add the max_epochs vs max_steps functionality
    label_type: long
    append_text: train
    max_epochs: !!int 4
    loader_params:
        batch_size: !!int 2
        num_workers: !!int 4
        shuffle: True

    optimizer:
        type: adam_w
        params:
            lr: !!float 1e-5
            betas: [0.9,0.998]
            eps: !!float 1e-8

    scheduler: null

    criterion:
        type: CrossEntropyLoss
        params: null

    save_on : ##Best Model/Final Model Saving
      score: sklearn_acc
      desired: min
      best_path: './ckpts/recam/train/best_{}.pth'
      final_path: './ckpts/recam/train/final_{}.pth'


    checkpoint:
        checkpoint_dir: './ckpts/recam/'

    log_and_val_interval: !!int 500 ## Set to null if using different val and log intervals, Overrides log_interval nd val_interval

    val_interval: !!int 500 # Global steps
    log:
        log_interval: !!int 100 # Global Steps
        logger_params:
            model: gabertclozeqa
            trainer: cloze
            comment: "Trial for Logger and Trainer"
            log_dir: './logs/recam/train'
        log_label: 1
        values:
            loss: True
            metrics: True
            hparams: null

val:
    <<: *main
    append_text: val
    max_steps: null
    loader_params:
        batch_size: !!int 4
        num_workers: !!int 4
        shuffle: false
    # log:
    #     logger_params:
    #         model: two_layer_nn
    #         trainer: cloze
    #         comment: "Trial for Logger and Trainer"
    #         log_dir: './logs/cloze/eval'
    #     log_label: 1
    #     values:
    #         loss: true
    #         metrics: true
            # hparams: true
