main: &main
  name: cloze_base
  data_dir: ./data/imperceptibility/
  truncate_length: 512
  preprocessor:
    name: clozePreprocessor
    tokenizer:
      name: AutoTokenizer
      init_params:
        pretrained_model_name_or_path: "bert-large-uncased"

train: &train
  <<: *main
  file_path: ./data/imperceptibility/training_data/Task_1_train.jsonl
  split: train

val:
  <<: *main
  file_path: ./data/imperceptibility/training_data/Task_1_dev.jsonl
  split: val
test:
  <<: *main
