main: &main
  name: concreteness
  data_dir: ./data/Concreteness Ratings/
  # annotations:
  #   train: ./data/Concreteness Ratings/train/forty.csv
  #   val: ./data/Concreteness Ratings/val/forty.csv
  #   test:
  text_cols:
    - Word
  label_col: Conc.M
  preprocessor:
    name: glove
    embedding:
      name: glove
    tokenizer:
      name: glove
      init_params:
        cache: ./embeddings/
      init_vector_params:
        tokenizer_file_paths:
          - ./data/Concreteness Ratings/train/forty.csv
          - ./data/Concreteness Ratings/val/forty.csv
        fields:
          - Word

train: &train
  <<: *main
  file_path: ./data/Concreteness Ratings/train/forty.csv
  split: train

val:
  <<: *main
  file_path: ./data/Concreteness Ratings/val/forty.csv
  split: val
test:
  <<: *main
