main: &main
  name: transformers_concreteness
  data_dir: ./data/Concreteness Ratings/
  # annotations:
  #   train: ./data/Concreteness Ratings/train/forty.csv
  #   val: ./data/Concreteness Ratings/val/forty.csv
  #   test:
  text_cols:
    - Word
  label_col: Conc.M
  preprocessor:
    name: transformersConcretenessPreprocessor
    tokenizer:
      name: autoTokenizer
      init_params:
        pretrained_model_name_or_path: bert-large-uncased

train: &train
  <<: *main
  file_path: ./data/Concreteness Ratings/train/forty.csv
  split: train

val:
  <<: *main
  file_path: ./data/Concreteness Ratings/val/forty.csv
  split: val
test:
  <<: *main